//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNX.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHOIXE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHOIXE()
        {
            this.GHE = new HashSet<GHE>();
        }
    
        public string MAPHOI { get; set; }
        public Nullable<int> MATUYEN { get; set; }
        public Nullable<int> MAKH { get; set; }
        public string MALICH { get; set; }
        public Nullable<System.DateTime> NGAYTAOVE { get; set; }
        public Nullable<System.DateTime> NGAYDATVE { get; set; }
        public Nullable<decimal> THANHTIEN { get; set; }
        public string TRANGTHAIPHOI { get; set; }
        public string PTTHANHTOAN { get; set; }
        public Nullable<int> MA_XE { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LICHCHAY LICHCHAY { get; set; }
        public virtual TUYENDUONG TUYENDUONG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GHE> GHE { get; set; }
    }
}
