//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNX.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAM
    {
        public int MATRAM { get; set; }
        public Nullable<int> MATUYEN { get; set; }
        public string TENTRAM { get; set; }
        public string DIACHI { get; set; }
        public string TRANGTHAITRAM { get; set; }
    
        public virtual TUYENDUONG TUYENDUONG { get; set; }
    }
}
