//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNX.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENDUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENDUONG()
        {
            this.PHOIXE = new HashSet<PHOIXE>();
            this.TRAM = new HashSet<TRAM>();
        }
    
        public int MATUYEN { get; set; }
        public string DIADIEMDI { get; set; }
        public string DIADIEMDEN { get; set; }
        public string THOIGIANCHAY { get; set; }
        public string DODAI { get; set; }
        public string TRANGTHAITUYEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHOIXE> PHOIXE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAM> TRAM { get; set; }
    }
}
