//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNX.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class XE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public XE()
        {
            this.GHE = new HashSet<GHE>();
        }
    
        public int MAXE { get; set; }
        public string TENXE { get; set; }
        public string HANGXE { get; set; }
        public Nullable<int> SOGHE { get; set; }
        public string HINHANH { get; set; }
        public Nullable<decimal> GIAVE { get; set; }
        public string BIENXE { get; set; }
        public string TRANGTHAIXE { get; set; }
        public Nullable<int> MANV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GHE> GHE { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
